export const reportDetailsData = [
  { id: 1, title: "Transaction id", value: 91 },
  { id: 2, title: "Created On", value: "06-10-2023" },
  { id: 3, title: "Created By", value: "MVerma" },
  { id: 4, title: "Requistion Number", value: 100365 },
  { id: 5, title: "Requistion Year", value: 2023 },
  { id: 6, title: "Company Code", value: 9008 },
  { id: 7, title: "Shoping Control No", value: 6234640 },
  { id: 8, title: "Vendor", value: 10073952 },
  { id: 9, title: "Beneficiary Name", value: "Tushar Pateroleum Pvt,Ltd.com" },
  { id: 10, title: "Payment Code", value: 202 },
  { id: 11, title: "Payment Due Date", value: "29-09-2023" },
  { id: 12, title: "initating Party Name", value: "" },
  { id: 13, title: "Request Excution Date", value: "" },
  { id: 14, title: " Debtor Org Name", value: "Reliance Retail Ltd" },
  { id: 15, title: "Debtor Name", value: "MVerma" },
  { id: 16, title: "Account Number", value: "" },
  { id: 17, title: "Charge Bearer", value: "DEBT" },
  { id: 18, title: "Created Account Currency", value: "INR" },
  { id: 19, title: " Invoice Amount", value: 174.0 },
  { id: 20, title: "Mis Charge", value: 1000.0 },
];
